import os

server_template = """# Config created by startup.py
MASTER_NAME = {USER}
CONDOR_HOST = {HOSTNAME}
COLLECTOR_HOST = $(CONDOR_HOST):{PORT}
SCHEDD_NAME = {USER}@{HOSTNAME}

RELEASE_DIR = {CONDOR_INSTALL}

USE_SHARED_PORT = True
SHARED_PORT_ARGS = -p {PORT}

SHARED_PORT_PORT = {PORT}

UID_DOMAIN = {USER}-condor
DAEMON_LIST = MASTER, COLLECTOR, NEGOTIATOR, SCHEDD

START = True
SUSPEND = False
PREEMPT = False
KILL = False

PRIVATE_NETWORK_NAME = $(FULL_HOSTNAME)
TCP_FORWARDING_HOST = {HOSTNAME}

SEC_PASSWORD_FILE = {PASSWORDFILE}
SEC_DEFAULT_AUTHENTICATION_METHODS = PASSWORD, FS

SCRATCH_DIR = {LOGDIR}
HOME_DIR = $ENV(HOME:/global/homes/{FIRSTLETTER}/{USER})
LOCAL_DIR = $(SCRATCH_DIR)/$(HOSTNAME)

ALLOW_READ = 128.55.*, 10.*, $(FULL_HOSTNAME), {HOSTNAME}, *
ALLOW_WRITE = 128.55.*, 10.*, $(FULL_HOSTNAME), {HOSTNAME}, *

ALLOW_ADVERTISE_STARTD = $(ALLOW_WRITE)
ALLOW_ADVERTISE_SCHEDD = $(ALLOW_WRITE)
ALLOW_WRITE_STARTD = $(ALLOW_WRITE)
ALLOW_READ_STARTD = $(ALLOW_WRITE)
ALLOW_WRITE_SCHEDD = $(ALLOW_WRITE)
ALLOW_READ_SCHEDD = $(ALLOW_WRITE)
ALLOW_ADVERTISE_MASTER = $(ALLOW_WRITE)

NEGOTIATOR.ALLOW_READ = $(ALLOW_READ)
NEGOTIATOR.ALLOW_WRITE = $(ALLOW_WRITE)

ALLOW_NEGOTIATOR = *

QUEUE_SUPER_USERS = root, condor, condor_pool, {USER}

NEGOTIATOR_INTERVAL = 5

COLLECTOR_DEBUG = D_FULLDEBUG
NEGOTIATOR_DEBUG = D_FULLDEBUG
MATCH_DEBUG = D_FULLDEBUG
SCHEDD_DEBUG = D_FULLDEBUG
"""

worker_template = """########################################
# Config created by startup.py
# Host and port
CONDOR_HOST = {HOSTNAME}:{PORT}
COLLECTOR_HOST = $(CONDOR_HOST)?sock=collector
SCHEDD_NAME = {USER}@{HOSTNAME}

FILESYSTEM_DOMAIN = $(HOSTNAME)
UID_DOMAIN = $(HOSTNAME)

USE_CCB = True
CCB_ADDRESS = $(CONDOR_HOST)

DAEMON_LIST = MASTER, STARTD, SHARED_PORT

QUEUE_ALL_USERS_TRUSTED = True

START = True
SUSPEND = False
PREEMPT = False
KILL = False

use feature:PartitionableSlot
use feature : GPUs

USE_SHARED_PORT = True

SCRATCH_DIR = {LOGDIR}
HOME_DIR = $ENV(HOME:/global/homes/{FIRSTLETTER}/{USER})
LOCAL_DIR = $(SCRATCH_DIR)/$(HOSTNAME)

RELEASE_DIR = {CONDOR_INSTALL}

SEC_PASSWORD_FILE = {PASSWORDFILE}
SEC_DEFAULT_AUTHENTICATION_METHODS = PASSWORD, FS

ALLOW_READ = 128.55.*, 10.*
ALLOW_WRITE = 128.55.*, 10.*

SCHEDD_DEBUG = D_FULLDEBUG
COLLECTOR_DEBUG = D_FULLDEBUG
NEGOTIATOR_DEBUG = D_FULLDEBUG
MATCH_DEBUG = D_FULLDEBUG
SCHEDD_DEBUG = D_FULLDEBUG
STARTER_ALLOW_RUNAS_OWNER = True

########################################"""


if __name__ == '__main__':
    env_vars = {key: os.environ.get(key)
                for key in ["USER", "PORT", "HOSTNAME", "PASSWORDFILE", "CONDOR_INSTALL", "LOGDIR"]}
    env_vars["FIRSTLETTER"] = env_vars["USER"][0]
    # Prints a file to be copy/pasted into a config file for cori
    with open("conf_worker.conf", 'w') as config:
        config.write(worker_template.format(**env_vars))

    with open("conf_server.conf", 'w') as config:
        config.write(server_template.format(**env_vars))
