import os

server_template = """# Config created by startup.py
MASTER_NAME = {USER}
CONDOR_HOST = {HOSTNAME}
COLLECTOR_HOST = $(CONDOR_HOST):{PORT}
SCHEDD_NAME = {USER}@{HOSTNAME}
CONDOR_ADMIN = {USER}@nersc.gov

RELEASE_DIR = {CONDOR_INSTALL}

USE_SHARED_PORT = True
SHARED_PORT_ARGS = -p {PORT}

SHARED_PORT_PORT = {PORT}

UID_DOMAIN = {USER}-condor
DAEMON_LIST = MASTER, COLLECTOR, NEGOTIATOR, SCHEDD

START = True
SUSPEND = False
PREEMPT = False
KILL = False

PRIVATE_NETWORK_NAME = $(FULL_HOSTNAME)
TCP_FORWARDING_HOST = {HOSTNAME}

SEC_PASSWORD_FILE = {PASSWORDFILE}
SEC_DEFAULT_AUTHENTICATION_METHODS = PASSWORD, FS

#SCRATCH_DIR = {LOGDIR}
HOME_DIR = $ENV(HOME:/global/homes/{FIRSTLETTER}/{USER})
#LOCAL_DIR = $(SCRATCH_DIR)/$(HOSTNAME)

ALLOW_READ = 128.55.*, 10.*, $(FULL_HOSTNAME), {HOSTNAME}, *
ALLOW_WRITE = 128.55.*, 10.*, $(FULL_HOSTNAME), {HOSTNAME}, *

ALLOW_ADVERTISE_STARTD = $(ALLOW_WRITE)
ALLOW_ADVERTISE_SCHEDD = $(ALLOW_WRITE)
ALLOW_WRITE_STARTD = $(ALLOW_WRITE)
ALLOW_READ_STARTD = $(ALLOW_WRITE)
ALLOW_WRITE_SCHEDD = $(ALLOW_WRITE)
ALLOW_READ_SCHEDD = $(ALLOW_WRITE)
ALLOW_ADVERTISE_MASTER = $(ALLOW_WRITE)

NEGOTIATOR.ALLOW_READ = $(ALLOW_READ)
NEGOTIATOR.ALLOW_WRITE = $(ALLOW_WRITE)

ALLOW_NEGOTIATOR = *

QUEUE_SUPER_USERS = root, condor, condor_pool, {USER}

NEGOTIATOR_INTERVAL = 5

COLLECTOR_DEBUG = D_FULLDEBUG
NEGOTIATOR_DEBUG = D_FULLDEBUG
MATCH_DEBUG = D_FULLDEBUG
SCHEDD_DEBUG = D_FULLDEBUG
"""

server_template = """# Config created by /root/config/startup.py
MASTER_NAME = {USER}
CONDOR_HOST = {HOSTNAME}
COLLECTOR_HOST = $(CONDOR_HOST):{PORT}
SCHEDD_NAME = {USER}@{HOSTNAME}

USE_SHARED_PORT = True
SHARED_PORT_ARGS = -p {PORT}

SHARED_PORT_PORT = {PORT}

UID_DOMAIN = {USER}-condor
DAEMON_LIST = MASTER, COLLECTOR, NEGOTIATOR, SCHEDD

START = True
SUSPEND = False
PREEMPT = False
KILL = False

# Machine resource settings
NUM_SLOTS = 6

PRIVATE_NETWORK_NAME = $(FULL_HOSTNAME)
TCP_FORWARDING_HOST = {HOSTNAME}


SEC_PASSWORD_FILE = /etc/condor/passwords.d/{PASSWORDFILE}
SEC_DEFAULT_AUTHENTICATION_METHODS = PASSWORD, FS

ALLOW_READ = 128.55.*, 10.*, $(FULL_HOSTNAME), {HOSTNAME}, *
ALLOW_WRITE = 128.55.*, 10.*, $(FULL_HOSTNAME), {HOSTNAME}, *

ALLOW_ADVERTISE_STARTD = $(ALLOW_WRITE)
ALLOW_ADVERTISE_SCHEDD = $(ALLOW_WRITE)
ALLOW_WRITE_STARTD = $(ALLOW_WRITE)
ALLOW_READ_STARTD = $(ALLOW_WRITE)
ALLOW_WRITE_SCHEDD = $(ALLOW_WRITE)
ALLOW_READ_SCHEDD = $(ALLOW_WRITE)
ALLOW_ADVERTISE_MASTER = $(ALLOW_WRITE)

NEGOTIATOR.ALLOW_READ = $(ALLOW_READ)
NEGOTIATOR.ALLOW_WRITE = $(ALLOW_WRITE)

ALLOW_NEGOTIATOR = *

QUEUE_SUPER_USERS = root, condor, condor_pool, {USER}

COLLECTOR_DEBUG = D_FULLDEBUG
NEGOTIATOR_DEBUG = D_FULLDEBUG
MATCH_DEBUG = D_FULLDEBUG
SCHEDD_DEBUG = D_FULLDEBUG
"""


if __name__ == '__main__':
    env_vars = {key: os.environ.get(key)
                for key in ["USER", "PORT", "HOSTNAME", "PASSWORDFILE", "CONDOR_INSTALL", "LOGDIR"]}
    env_vars["FIRSTLETTER"] = env_vars["USER"][0]

    with open("/etc/condor/config.d/95-NERSC.conf", 'w') as config:
        config.write(server_template.format(**env_vars))
